// Regenerates the API types from the FastAPI schema (`npm run gen:api`):
// - src/api/schema.gen.ts: openapi-typescript over `bsim openapi` (the fixture app's schema);
// - src/api/drift.gen.ts: a compile-time check that every hand-written type in src/api/types.ts
//   with a schema of the same name has the same fields and fits the schema (it may narrow a
//   `string` to a union of literals). `tsc -b` then fails when the backend and viewer drift.
// `--check` regenerates in memory and fails if the committed files are out of date (CI).
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const web = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const api = join(web, 'src', 'api')
const check = process.argv.includes('--check')

const tmp = mkdtempSync(join(tmpdir(), 'bsim-openapi-'))
const schemaPath = join(tmp, 'openapi.json')
try {
  execFileSync('uv', ['run', 'bsim', 'openapi', '--out', schemaPath], {
    cwd: resolve(web, '..'),
    stdio: ['ignore', 'ignore', 'inherit'],
  })
  const schema = JSON.parse(readFileSync(schemaPath, 'utf-8'))
  const header = '// Generated by `npm run gen:api` from the FastAPI schema. Do not edit.\n\n'
  const files = {
    'schema.gen.ts': header + astToString(await openapiTS(schema)),
    'drift.gen.ts': header + driftCheck(Object.keys(schema.components.schemas)),
  }
  const stale = []
  for (const [name, text] of Object.entries(files)) {
    const path = join(api, name)
    let old = null
    try {
      old = readFileSync(path, 'utf-8').replace(/\r\n/g, '\n')
    } catch {}
    if (old === text) continue
    if (check) stale.push(name)
    else writeFileSync(path, text)
  }
  if (stale.length) {
    console.error(`out of date: ${stale.join(', ')} (run \`npm run gen:api\`)`)
    process.exitCode = 1
  }
} finally {
  rmSync(tmp, { recursive: true, force: true })
}

function driftCheck(schemaNames) {
  const hand = readFileSync(join(api, 'types.ts'), 'utf-8')
  const exported = new Set([...hand.matchAll(/^export (?:interface|type) (\w+)/gm)].map((m) => m[1]))
  const shared = schemaNames.filter((n) => exported.has(n)).sort()
  const lines = [
    "import type { components } from './schema.gen'",
    "import type * as H from './types'",
    '',
    "type S = components['schemas']",
    'type SameKeys<A, B> = [Exclude<keyof A, keyof B>, Exclude<keyof B, keyof A>] extends [never, never] ? true : false',
    'type Fits<A, B> = [A] extends [B] ? true : false',
    'type Ok<T extends true> = T',
    '',
    ...shared.map((n) => `export type ${n}Keys = Ok<SameKeys<H.${n}, S['${n}']>>\nexport type ${n}Fits = Ok<Fits<H.${n}, S['${n}']>>`),
    '',
  ]
  return lines.join('\n')
}
